M48
; DRILL file {KiCad 8.0.0} date 2024-08-30T12:49:42-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-30T12:49:42-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X168.1Y-150.3
X204.1Y-123.3
X205.0Y-150.3
T2
X152.0Y-124.0
X152.0Y-135.43
X220.9Y-124.1
X220.9Y-135.53
M30
